### PR TITLE
Fix code highlighting theme-ing

### PR DESCRIPTION
**Pull request by montehurd**
https://phabricator.wikimedia.org/T180846

`enwiki > Lua (programming language) > Syntax`

# Before
screen shot 2017-11-17 at 12 48 11 pm
screen shot 2017-11-17 at 12 48 20 pm

# After
screen shot 2017-11-20 at 5 07 53 pm
screen shot 2017-11-20 at 5 08 01 pm

### CODE REVIEW

**Comment by berndsi** [comment]
Can we change the colors? The text color of the function highlight ("factorial") on the dark theme is really hard to read for me.

**Comment by montehurd** [comment]
@berndsi ah good point. should maybe pause on merging this until we get design feedback to see if that's a blocker

**Comment by montehurd** [comment]
@berndsi that blue should be easy to target. i'll ping carolyn on the ticket.

**Comment by montehurd** [comment]
Prob hold off on merging until we get design feedback on the [phab ticket](https://phabricator.wikimedia.org/T180846).

**Comment by berndsi** [comment]
@montehurd Thanks for the color tweak. Do you have an updated screenshot available for the last example?

**Comment by montehurd** [comment]
Was able to track down pre-made dark and sepia settings (see 'native' and 'perldoc' [here](https://github.com/richleland/pygments-css)) for the `pygments` extension so we'll get good coverages for all of the [languages](http://pygments.org/languages/) it supports.

**Comment by montehurd** [comment]
Carolyn and I reviewed a few dozen examples across various programming languages articles and the pre-made colors looked to have good contrast.

**Comment by montehurd** [comment]
@berndsi @niedzielski have a sec to take a peek at the last commits I added?

**Comment by berndsi** [comment]
The updated screenshots look good to me.

**Comment by montehurd** [comment]
@dbrant 

> The overrides for "dark" can probably be duplicated for "black," too.

Good idea! I'll submit a follow-on once both are merged :)

**Pull request merged**
