### PR TITLE
Add Black theme.

### PR DESCRIPTION
**Pull request by dbrant**
This will correspond with the upcoming addition of a "black" theme in the Android app, and can later be adopted by iOS, as well.

### CODE REVIEW

**Comment by montehurd** [comment]
@dbrant oh would you mind adding a quick update to the top of the changelog for this?

**Comment by dbrant** [comment]
@montehurd I've been using gerrit for too long :(  I've added to the changelog, but also seem to have made an (unnecessary?) rebase. Let me know if I need to re-do anything...

**Comment by montehurd** [comment]
@dbrant ooh yeah that got funky...

I have the pre-rebase version locally and can push that if you want...

**Comment by montehurd** [comment]
@dbrant here it is if you want to re-start from there:
https://github.com/montehurd/wikimedia-page-library/commits/black

**Pull request closed without merging**
