### PR TITLE
Update package-lock

### PR DESCRIPTION
**Pull request by mdholloway**
Needed to update growl (a dependency of mocha), which has a security
vulnerability at 1.9.2.

https://github.com/mochajs/mocha/issues/2973
https://nodesecurity.io/advisories/146

### CODE REVIEW

**Comment by mdholloway** [comment]
Yikes, I didn't mean to make things worse!  Should be fixed with the update. 

My initial thought was just to nuke package-lock and `npm install`, which is what I did.

Sure enough, `npm audit` reported the same here, though.  So I ran `npm audit fix` once, which improved things considerably:

`found 98 vulnerabilities (50 low, 46 moderate, 2 high) in 24902 scanned packages`

And after running once more:

`found 19 vulnerabilities (8 low, 9 moderate, 2 high) in 24377 scanned packages`

**Comment by niedzielski** [comment]
Thanks @mdholloway. Would you [allow changes to this PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests)? There are couple patches I need to stack on top that are currently in #146.

**Comment by mdholloway** [comment]
@niedzielski Thanks!  I'll take it for a spin in the Android app before merging.

**Comment by mdholloway** [comment]
Looks good in the app.

**Pull request merged**
