### PR TITLE
Add getSelectionInfo

### PR DESCRIPTION
**Pull request by joewalsh**
Add `getSelectionInfo` to `pagelib.c1.InteractionHandler`
https://phabricator.wikimedia.org/T228686

### CODE REVIEW

**Comment by berndsi** [comment]
@joewalsh Thank you! This works well. It would be good to add documentation for this to the pcs.md file. Is the action/event for the text selection going to be a different PR?

**Comment by joewalsh** [comment]
@berndsi I think the action/event may have been a miscommunication in the PR - it looked like in the android code it only needed to be a read of selection information, not an an action when selection changes - @sharvaniharan is this correct?

**Comment by joewalsh** [comment]
@berndsi I updated the doc

**Comment by berndsi** [comment]
@joewalsh I think you're correct. My bad. Should we add in the docs that `section` may be null (in the case of the selected text being outside of a section, e.g. in the description)?

**Comment by joewalsh** [comment]
@berndsi done

**Pull request merged**
