### PR TITLE
Fix: update the article description text styles from px to em

### PR DESCRIPTION
**Pull request by cooltey**
Didn't see it happen on the iOS app but in the Android app, updating the font size will not change the article description text size.

ezgif com-resize

### CODE REVIEW

**Comment by montehurd** [comment]
Just curious, on Android how are you adjusting the size css?

On iOS there's a single css selector we can use which proportionally scales everything (including spacing) regardless of units `em`/`px` etc.

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW16

Wonder if the standard version https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust would work for Android too?

**Comment by cooltey** [comment]
> 
> 
> Just curious, on Android how are you adjusting the size css?
> 
> On iOS there's a single css [selector](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW16) we can [use](https://github.com/wikimedia/wikipedia-ios/blob/develop/Wikipedia/Code/WKWebView%2BWMFWebViewControllerJavascript.m#L12) which proportionally scales everything (including spacing and images) regardless of units `em`/`px` etc.
> 
> Wonder if the standard version of the [selector](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust) would work for Android's minimum OS target too?

In Android we use [setDefaultFontSize()](https://developer.android.com/reference/android/webkit/WebSettings#setDefaultFontSize(int)) to set the font size. 

Ideally, it should work on the `px` as well, but I am not sure why it does not work in this specific case. Maybe Google has changed the logic of adjusting text size in the WebView component (since it can be updated through Google Play).

I think the selector would work for the Android's minimum OS target.

**Comment by montehurd** [comment]
Does `setTextZoom` work?

**Comment by cooltey** [comment]
> 
> 
> Does `setTextZoom` work?

Thanks, @montehurd!
Not sure why we didn't use it before, maybe it is because it requires `minSdkVersion = 14`. Since we increase it to `minSdkVersion = 21`, I think we can have a try on this.

**Comment by cooltey** [comment]
It can be fixed on Android client side.

**Comment by cooltey** [comment]
Reopen this PR due to the feedback from: https://phabricator.wikimedia.org/T230635

**Pull request merged**
