### PR TITLE
Fix: add Web Components polyfill to demos

### PR DESCRIPTION
**Pull request by niedzielski**
Add Web Components polyfill to each demo. I couldn't find
webcomponents-loader.js as an NPM distributable so I used the one hosted
for Polymer projects.

https://github.com/webcomponents/webcomponentsjs
https://github.com/webcomponents/webcomponentsjs/issues/397
https://www.npmjs.com/package/webcomponents.js
https://www.polymer-project.org/2.0/start/quick-tour

### CODE REVIEW

**Comment by niedzielski** [comment]
@montehurd, please try in Safari.

**Comment by montehurd** [comment]
Hmm it seems to be stuck in some sort of redirect loop...

**Comment by montehurd** [comment]
- safari : redirect loop?
- firefox: blank
- chrome: seems fine

**Comment by niedzielski** [comment]
Sheesh, this doesn't work at all? WTF... What version of Firefox are you running? This seems to work correctly on Firefox v54.0 for Linux.

**Comment by montehurd** [comment]
Looks like I was on 49.0.1. I updated and will re-test when I get a chance.

**Comment by montehurd** [comment]
The demo html files start working if you add a `link` tag for 'wikimedia-page-library-transform.css' to each file. Only problem is the polyfill custom control tag is still doing some weird redirect loop on safari and firefox...

**Comment by montehurd** [comment]
> The demo html files start working...

on Safari and Firefox that is

**Comment by niedzielski** [comment]
@montehurd the style links are definitely missing! I'm disappointed that at least Firefox isn't working :[

**Comment by montehurd** [comment]
Could it be refactored a bit to use a CSS and JS file instead of `<link rel=import href=ControlPanel.html>`?

**Comment by niedzielski** [comment]
You could refactor the JavaScript and CSS easily but I'm not sure how you would inject the ControlPanel HTML into the page without extra tooling.

**Comment by montehurd** [comment]
Given the compatibility issues, do you think we should consider more vanilla JS ways of adding control panel elements to demo pages? I think the way you did it is super cool though :)

**Comment by niedzielski** [comment]
I'm fine with exploring other options like iframe.

**Comment by niedzielski** [comment]
@montehurd, please try once more.

**Comment by montehurd** [comment]
Tested on Safari, Chrome and Firefox.

**Comment by niedzielski** [comment]
Thank heavens! No it was just WIP cause I thought it was working before and then it wasn't and I couldn't really verify on my machine.

**Pull request merged**
