### PR TITLE
Fix: brick, pie, bar, and stacked bar chart theming

### PR DESCRIPTION
**Pull request by niedzielski**
https://phabricator.wikimedia.org/T179128

### CODE REVIEW

**Comment by niedzielski** [comment]
@montehurd can you take a peek at these PRs? This one's already stale but doesn't have any feedback.

**Comment by montehurd** [comment]
@niedzielski will do! i'm jumping back on these pagelib PRs today :)

**Comment by montehurd** [comment]
This is great! Just noticed a couple small issues when proofing in dark mode with the theme demo:

- Looks like the single statistic bar color isn't being excluded from override:
screen shot 2018-06-01 at 4 27 39 pm
screen shot 2018-06-01 at 4 31 13 pm

- Also wondering if we could/should exclude the color of the text overlaying these bars:
screen shot 2018-06-01 at 4 27 47 pm
screen shot 2018-06-01 at 4 31 20 pm

**Comment by niedzielski** [comment]
@montehurd, ready for review!

> single statistic bar color
This is a Template:Composition_bar which requires the templateeditor permission to edit and I do not have it yet. While I want to see this composition bar issue fixed, I included as many other bonus fixes as I could as part of this series of patches and I believe it covers the original bug reported.

> Also wondering if we could/should exclude the color of the text overlaying these bars:
The CSS for this isn't pretty but "fixed" :]

**Pull request merged**
