### PR TITLE
Chore: add JavaScript type-checking support

### PR DESCRIPTION
**Pull request by niedzielski**
Add (initial and minimal) support for strict JavaScript typing using
TypeScript. This is the bare minimum implementation including a
conversion of one file. Subsequent PRs will piecewise revise the
codebase.

### CODE REVIEW

**Comment by montehurd** [comment]
This is amazing. I'm going to have to do a quick Type Script crash course before I review... but looks pretty great!

**Comment by niedzielski** [comment]
@montehurd, please make sure your editor provides autocompletion! It's goes really great with typing!

**Comment by montehurd** [comment]
@niedzielski ooh looks like there's an atom plugin... https://github.com/TypeStrong/atom-typescript

**Comment by niedzielski** [comment]
@montehurd, I certainly don't mean to dictate your choice of editors but if you have any curiosity about [VSCode](https://code.visualstudio.com/), now is the perfect time to try it out!

**Comment by niedzielski** [comment]
@montehurd, is there anything I can do to help move this patch forward?

**Comment by niedzielski** [comment]
@montehurd, I understand that adding new TypeScript syntax has a learning curve and requires additional build steps. Would there be more interest in merging a PR if it had no functional impact?  TypeScript also has the ability to type check plain vanilla JavaScript and JSDocs but I don't want to invest a bunch of time if there isn't interest in getting it merged.

**Comment by montehurd** [comment]
@niedzielski 

Hey when I try to integrate this on iOS I'm seeing this msg:

> ERROR in ./src/transform/index.js
> Module not found: Error: Can't resolve 'ts-loader' in '/Users/montehurd/wikimedia-page-library'
> resolve 'ts-loader' in '/Users/montehurd/wikimedia-page-library'

Any ideas?

**Comment by montehurd** [comment]
I tried adding `"ts-loader": "4.3.0"` to the app's devDependencies but no luck...

**Comment by niedzielski** [comment]
Is it too silly to ask: did you do an `npm install`?

**Comment by montehurd** [comment]
I tried a few different things. It looks like it's this issue: https://github.com/npm/npm/issues/10013

Other branches work correctly but this one always says: `npm WARN update-linked node_modules/wikimedia-page-library needs updating to 6.0.8 from 6.0.7 but we can't, as it's a symlink`

**Comment by niedzielski** [comment]
@montehurd, I've upgraded the dependencies this patch introduces to today's latest. Can you try upgrading your [Node.js install](https://nodejs.org/en/) and `rm -rf node_modules && npm i` on this PR?

**Pull request merged**
