### PR TITLE
Add demo for CollapseTable transform

### PR DESCRIPTION
**Pull request by berndsi**
Also running ThemeTransform.classifyElements(), just in case.

### CODE REVIEW

**Comment by berndsi** [comment]
@niedzielski I just realized that the ThemeTransform demo has a checkbox for turning on CollapseTable. So, I guess this PR is not useful. Instead I've added the article to the Them demo (PR #154).
Unfortunately the RTL issue is present there as well.

**Comment by niedzielski** [comment]
@berndsi, up to you. The theming demo is enormous and takes a while to load so debugging issues is slower. I'm happy to have some overlap with the demos, especially if this is more unit focused.

**Comment by berndsi** [comment]
@niedzielski Yeah, the Theme demo is super slow. I wonder how hard it would be to lazy load the article content.

**Comment by berndsi** [comment]
Maybe the "all" case could be solved by adding a button to load all content? But by default only load the first one, so a user can set all the control parameters (theme, collapseTables, direction, ...) before loading all articles.

**Comment by niedzielski** [comment]
That would be a nice improvement.

**Comment by montehurd** [comment]
> Maybe the "all" case could be solved by adding a button to load all content? But by default only load the first one, so a user can set all the control parameters (theme, collapseTables, direction, ...) before loading all articles.

This is more or less what the "everything demo" I'm chipping away at does. Sorry it's taking so long!

**Comment by berndsi** [comment]
@montehurd working on a better demo.

**Pull request closed without merging**
